# Generated by Django 4.0.4 on 2022-07-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('platform', models.CharField(max_length=20)),
                ('problems', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
