# Generated by Django 4.0.6 on 2022-08-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChefProfile',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=20)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GFGProfile',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=20)),
                ('problems', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HackerRankProfile',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=20)),
                ('badges', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='LeetCodeProfile',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=20)),
                ('problems', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
