# Generated by Django 4.0.4 on 2022-07-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='codingprofile',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
