# Generated by Django 4.0.4 on 2022-07-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_codingprofile_id_alter_codingprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChefProfile',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=20)),
                ('stars', models.PositiveIntegerField(default=1)),
                ('rating', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HackerRankProfile',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=20)),
                ('stars', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LeetCodeProfile',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=20)),
                ('problems', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='CodingProfile',
            new_name='GFGProfile',
        ),
    ]
