# Generated by Django 4.0.4 on 2022-07-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_codechefprofile_hackerrankprofile_leetcodeprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codechefprofile',
            name='stars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
